site_name: BeamMP Docs
site_url: https://docs.beammp.com/
site_description: This website serves as the new BeamMP Documentation site for general self serve support, guides and documentation. Best of all it is source available so you the community can help us to A. keep it up-to-date and B. providing the content you require.
repo_url: https://github.com/beammp/docs
repo_name: beammp/docs
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2019 - 2024 BeamMP Mod Team

theme:
  language: en
  name: material
  logo: assets/core/beammp_dark.png
  logo_dark: assets/core/beammp_light.png
  favicon: assets/core/favicon.png
  custom_dir: overrides
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tooltips
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.tracking
    - navigation.indexes
    - toc.follow
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - stylesheets/custom.css
extra_javascript:
  - javascript/custom.js
extra:  
  analytics:
    provider: google
    property: G-8T6ETLZCMC
  status:
    new: Recently added
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/beammp
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/beamng_mp
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/beammp
  alternate:
    - name: English
      link: / 
      lang: en
    - name: Español
      link: /es/ 
      lang: es
    - name: Deutsch
      link: /de/
      lang: de
    - name: Français
      link: /fr/
      lang: fr
    - name: Italiano
      link: /it/
      lang: it
    - name: Pусский
      link: /ru/
      lang: ru
  homepage: /

plugins:
  - search
  - social
  - tags
  - i18n:
      reconfigure_material: true
      fallback_to_default: true
      docs_structure: folder
      languages:
        - locale: es
          name: Español
          build: true
          nav_translations:
            Home: Inicio
            Getting started: Empezando
            Playing BeamMP: Jugando a BeamMP
            Installing BeamMP: Instalación de BeamMP
            Error Codes: Códigos de error
            Customizing your setup: Personaliza tu configuración
            Using BeamMP: Usando BeamMP
            Running a Server: Ejecutando un Servidor
            Server Installation: Instalación del Servidor
            Server Maintenance: Manutención del Servidor
            Error Codes: Códigos de error
            Server Manual: Manual del Servidor
            Mod & Resource Creation: Creación de Mods y Recursos
            Client Side: Lado del Cliente
            Server Side: Lado del Servidor
            Support: Soporte
            Player FAQ: Preguntas frecuentes del jugador
            Game FAQ: Preguntas Frecuentes del Juego
            Server FAQ: Preguntas Frecuentes del Servidor
            Development Guides: Guías de Desarrollo
            Mod Creation: Creación de Mods
            UI Apps: Aplicaciones de IU
            IMGUI Windows: Ventanas IMGUI
            Lua Mods: Mods Lua
            Resource Creation: Creación de Recursos
            UI Apps: Aplicaciones de IU
            Snippets: Fragmentos de Código
            BeamNG Documentation: Documentación de BeamNG
            Installation: Instalación
            Helpful Snippets: Fragmentos Útiles
            Scripting Reference: Referencia de Scripting
            Mod (In-Game): Mod (En el Juego)
            Server: Servidor
            Contributing: Contribuir
            Getting Started: Primeros Pasos
            Community: Comunidad
        - locale: de
          name: Deutsch
          build: true
          nav_translations:
            Home: Zuhause
            Getting started: Erste Schritte
            Playing BeamMP: BeamMP spielen
            Installing BeamMP: BeamMP Installation
            Error Codes: Fehlercodes
            Customizing your setup: Konfiguration anpassen
            Using BeamMP: BeamMP verwenden
            Running a Server: Server ausführen
            Server Installation: Server Installation
            Server Maintenance: Server Wartung
            Error Codes: Fehlercodes
            Server Manual: Server Handbuch
            Mod & Resource Creation: Mod- & Ressourcenerstellung
            Client Side: Clientseite
            Server Side: Serverseite
            Support: Unterstützung
            Player FAQ: Spieler-FAQ
            Game FAQ: Spiel FAQ
            Server FAQ: Server FAQ
            Development Guides: Entwicklungsanleitungen
            Mod Creation: Mod-Erstellung
            UI Apps: UI-Anwendungen
            IMGUI Windows: IMGUI-Fenster
            Lua Mods: Lua-Mods
            Resource Creation: Ressourcenerstellung
            UI Apps: UI-Anwendungen
            Snippets: Code-Schnipsel
            BeamNG Documentation: BeamNG-Dokumentation
            Installation: Installation
            Helpful Snippets: Nützliche Codeausschnitte
            Scripting Reference: Scripting-Referenz
            Mod (In-Game): Mod (Im Spiel)
            Server: Server
            Contributing: Mitwirken
            Getting Started: Erste Schritte
            Community: Gemeinschaft
        - locale: fr
          name: Français
          build: true
          nav_translations:
            Home: Accueil
            Getting started: Démarrage
            Playing BeamMP: Jouer à BeamMP
            Installing BeamMP: Installation de BeamMP
            Error Codes: Codes d'erreur
            Customizing your setup: Personnalisation de votre configuration
            Using BeamMP: Utilisation de BeamMP
            Running a Server: Exécution d'un serveur
            Server Installation: Installation du serveur
            Server Maintenance: Maintenance du serveur
            Error Codes: Codes d'erreur
            Server Manual: Manuel du serveur
            Mod & Resource Creation: Création de mods et de ressources
            Client Side: Côté client
            Server Side: Côté serveur
            Support: Support
            Player FAQ: FAQ del giocatore
            Game FAQ: FAQ du jeu
            Server FAQ: FAQ du serveur
            Development Guides: Guides de développement
            Mod Creation: Création de mods
            UI Apps: Applications UI
            IMGUI Windows: Fenêtres IMGUI
            Lua Mods: Mods Lua
            Resource Creation: Création de ressources
            UI Apps: Applications UI
            Snippets: Extraits de code
            BeamNG Documentation: Documentation BeamNG
            Installation: Installation
            Helpful Snippets: Extraits Utiles
            Scripting Reference: Référence de script
            Mod (In-Game): Mod (En jeu)
            Server: Serveur
            Contributing: Contribution
            Getting Started: Premiers pas
            Community: Communauté
        - locale: it
          name: Italiano
          build: true
          nav_translations:
            Home: Home
            Getting started: Guida introduttiva
            Playing BeamMP: Giocare a BeamMP
            Installing BeamMP: Installazione di BeamMP
            Error Codes: Codici di errore
            Customizing your setup: Personalizza la tua configurazione
            Using BeamMP: Utilizzare BeamMP
            Running a Server: Eseguire un server
            Server Installation: Installazione del server
            Server Maintenance: Manutenzione del server
            Error Codes: Codici di errore
            Server Manual: Manuale del server
            Mod & Resource Creation: Creazione di Mod e Risorse
            Client Side: Lato client
            Server Side: Lato server
            Support: Supporto
            Player FAQ: FAQ del giocatore
            Game FAQ: FAQ del gioco
            Server FAQ: FAQ del server
            Development Guides: Guide allo Sviluppo
            Mod Creation: Creazione di Mod
            UI Apps: Applicazioni UI
            IMGUI Windows: Finestre IMGUI
            Lua Mods: Mod Lua
            Resource Creation: Creazione di Risorse
            UI Apps: Applicazioni UI
            Snippets: Frammenti di Codice
            BeamNG Documentation: Documentazione BeamNG
            Installation: Installazione
            Helpful Snippets: Snippet Utili
            Scripting Reference: Riferimento allo Scripting
            Mod (In-Game): Mod (In gioco)
            Server: Server
            Contributing: Contribuire
            Getting Started: Primi Passi
            Community: Comunità
        - locale: ru
          name: Pусский
          build: true
          nav_translations:
            Home: Главная
            Getting started: Начало работы
            Playing BeamMP: Игра в BeamMP
            Installing BeamMP: Установка BeamMP
            Error Codes: коды ошибок
            Customizing your setup: Настройка конфигурации
            Using BeamMP: Использование BeamMP
            Running a Server: Запуск сервера
            Server Installation: Установка сервера
            Server Maintenance: Обслуживание сервера
            Error Codes: коды ошибок
            Server Manual: Руководство по серверу
            Mod & Resource Creation: Создание модов и ресурсов
            Client Side: Сторона клиента
            Server Side: Сторона сервера
            Support: Поддержка
            Player FAQ: Игроки ЧаВо
            Game FAQ: Часто задаваемые вопросы об игре
            Server FAQ: Часто задаваемые вопросы о сервере
            Development Guides: Руководства по разработке
            Mod Creation: Создание модов
            UI Apps: Приложения интерфейса пользователя
            IMGUI Windows: Окна IMGUI
            Lua Mods: Lua-моды
            Resource Creation: Создание ресурсов
            UI Apps: Приложения интерфейса пользователя
            Snippets: Фрагменты кода
            BeamNG Documentation: Документация BeamNG
            Installation: Установка
            Helpful Snippets: Полезные фрагменты
            Scripting Reference: Справочник по скриптингу
            Mod (In-Game): Мод (в игре)
            Server: Сервер
            Contributing: Участие
            Getting Started: Начало работы
            Community: Сообщество
        - locale: en
          default: true
          name: English
          build: true
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - tables
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Getting started:
    - Playing BeamMP:
      - Installing BeamMP: game/getting-started.md
      - Error Codes: game/error-codes.md
      - Customizing your setup: game/tailoring.md
      - Using BeamMP: game/playing.md
    - Running a Server:
      - Server Installation: server/create-a-server.md
      - Port Forwarding: server/port-forwarding.md
      - Server Maintenance: server/server-maintenance.md
      - Error Codes: server/error-codes.md
      - Server Manual: server/manual.md
    - Mod & Resource Creation:  
      - Client Side: guides/mod-creation/client/getting-started.md
      - Server Side: guides/mod-creation/server/getting-started.md
  - Support:
    - Player FAQ: support/player-faq.md
    - Game FAQ: support/game-faq.md
    - Server FAQ: support/server-faq.md
  - Development Guides:
    - guides/index.md
    - Development Environment Setup: guides/beammp-dev/beammp-dev.md
    - Mod Creation:  
      - Client Mods: guides/mod-creation/client/getting-started.md
      - Client Scripting Reference: scripting/mod-reference.md
    - Resource Creation:  
      - Server Resources: guides/mod-creation/server/getting-started.md
      - Server Scripting Reference: scripting/server-reference.md
  - BeamNG Documentation:
    - beamng/index.md
    - Content Development:    
      - Introduction: beamng/dev/index.md
      - Coding:
        - UI Apps (HTML): beamng/dev/modding/ui-apps.md
        - IMGUI Windows (Lua): beamng/dev/modding/imgui-windows.md
        - Lua Mods (Scripts): beamng/dev/modding/lua-mods.md
      - Content:
        - Maps: beamng/dev/content/maps.md
        - Props: beamng/dev/content/props.md
        - Vehicles: beamng/dev/content/vehicles.md
    - Helpful Code Snippets: beamng/snippets.md
  - Scripting Reference:
    - Mod (In-Game): scripting/mod-reference.md
    - Server: 
      - V3.X (Latest): scripting/server/latest-server-reference.md
      - V2.X: scripting/server/v2-server-reference.md
  - Contributing:
    - Getting Started: contributing.md
  - Community:
    - General Information: community/index.md
    - Rules: community/rules.md
